config/routes.rb
Rails.application.routes.draw do

  resources :history

  get 'timesheet/index'
  # resources :budget_holders
  # resources :plants

  resources :projects do
    resources :plant_time_sheets
    resources :employee_time_sheets
    resources :time_sheet_cost_codes
    resources :crews do
      collection do
        get '/:id/plants_list', to: 'crews#plants_list'
        get '/:id/employees_list', to: 'crews#employees_list'
      end
    end

    resources :foremen do
      collection do
        get :crew
        get :project_foreman_list
        post :import
        get :download_template
      end
    end

    resources :plants do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employee_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plant_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :cost_codes do
      collection do
        get :select_cost_codes
        post :assign_cost_codes
        post :import
        get :download_template
      end
    end

    resources :other_managers do
      collection do
        post :import
        get :download_template
      end
    end


    resources :budget_holders do
      collection do
        post :import
        get :download_template
      end
    end

    resources :project_companies do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employees do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plants


  end

  resources :temporary_users
  devise_for :users, :controllers => {:sessions => "sessions", confirmations: 'confirmations' }

  # devise_for :users, controllers: {
  #     sessions: 'users/sessions',
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations'
  # }

  root to: 'admin_dashboard#dashboard'
  resources :client_companies
  resources :users

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

end

app/models/budget_holder.rb
class BudgetHolder < ApplicationRecord
  audited
  has_many :cost_codes
  belongs_to :employee
  belongs_to :project

  validates_uniqueness_of :employee_id, :scope => :project_id

  def self.import_file(file, user, project)
    if File.extname(file.original_filename) == '.csv'
      file_name = file.original_filename
      @budget_holders = []
      i = 0
      CSV.foreach("public/documents/#{file_name}", headers: true) do |row|
        begin
          i = i + 1

          if row[0].nil?
            return error = "Validation Failed. Employee Name Empty in File, Error on Row: #{i}"
          end

          employee = Employee.find_by_employee_name(row[0].strip)
          if employee.nil?
            return error = "Validation Failed. Employee must exist, Error on Row: #{i}"
          end

          budget_holder = project.budget_holders.find_by_employee_id(employee.id)
          if budget_holder.present?
            return error = "Validation Failed. Budget Holder already exist, Error on Row: #{i}"
          end
          unless @budget_holders.any? {|budget_holder| budget_holder.employee_id == employee.id}
            @budget_holders << project.budget_holders.new(employee_id: employee.id)
          end
        rescue => e
          return e.message
        end
      end
      if @budget_holders.empty?
        return error = "Validation Failed. Please Insert some data in File."
      end
      BudgetHolder.import @budget_holders
      error = 'Data imported successfully!'

    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then
      Roo::CSV.new(file.path, nil, :ignore)
    when ".xlsx" then
      Roo::Excelx.new(file.path)
    when ".xls" then
      Roo::Excel.new(file.path)
    else
      return false
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  audited
  belongs_to :client_company

  has_many :cost_codes, dependent: :destroy
  has_many :other_managers, dependent: :destroy
  has_many :plants, dependent: :destroy
  has_many :budget_holders, dependent: :destroy
  has_many :plant_types, dependent: :destroy
  has_many :employees, dependent: :destroy
  has_many :employee_types, dependent: :destroy
  has_many :foremen, dependent: :destroy
  has_many :employee_time_sheets, dependent: :destroy
  has_many :plant_time_sheets, dependent: :destroy
  has_many :time_sheet_cost_codes, dependent: :destroy
  has_many :project_companies

  has_many :users
  has_many :crews


  enum status: {
      Active: 0,
      Onhold: 1,
      Closed: 2
  }

  validates_uniqueness_of :project_name, :case_sensitive => false
  auto_strip_attributes :project_name


  # before_destroy :check_for_projects, prepend: true

  private

  # def check_for_projects
  #   if project_employees.any? || cost_codes.any? || other_managers.any? || plants.any? || budget_holders.any? ||
  #       plant_types.any? || employee_types.any? || foremen.any?
  #     errors[:base] << "cannot delete submission that has already been linked"
  #     return false
  #   end
  # end


end

app/controllers/budget_holders_controller.rb
class BudgetHoldersController < ApplicationController
  before_action :get_project, only: [:new, :show, :edit, :update, :create, :index, :destroy, :import]
  before_action :set_budget_holder, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /budget_holders
  # GET /budget_holders.json
  def index
    @budget_holders = @project.budget_holders
  end

  # GET /budget_holders/1
  # GET /budget_holders/1.json
  def show
  end

  # GET /budget_holders/new
  def new
    @budget_holder = BudgetHolder.new
  end

  # GET /budget_holders/1/edit
  def edit
  end

  # POST /budget_holders
  # POST /budget_holders.json
  def create
    if params[:budget_holder][:employee_ids][1].present?
      params[:budget_holder][:employee_ids].each do |employee_id|
        begin
          BudgetHolder.create(project_id: @project.id, employee_id: employee_id.to_i,
                              client_company_id: @project.client_company_id)
        rescue => e
          puts e.inspect
        end
      end
      redirect_to project_budget_holders_path(@project), notice: 'Budget Holder was successfully created.'
    else
      @budget_holder.errors.add(:base, 'Please select Budget Holder first.')
      render :action => 'new'
    end
  end

  # PATCH/PUT /budget_holders/1
  # PATCH/PUT /budget_holders/1.json
  def update
    respond_to do |format|
      if @budget_holder.update(budget_holder_params)
        format.html {redirect_to "/projects/#{@project.id}/budget_holders", notice: 'Budget holder was successfully updated.'}
        format.json {render :show, status: :ok, location: @budget_holder}
      else
        format.html {render :edit}
        format.json {render json: @budget_holder.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /budget_holders/1
  # DELETE /budget_holders/1.json
  def destroy
    begin
      if @budget_holder.nil? || CostCode.find_by_budget_holder_id(@budget_holder.id).present?
        respond_to do |format|
          format.js
        end
      else
        @budget_holder.destroy
        @destroy = true
        respond_to do |format|
          format.js
        end
      end
    rescue => e
      redirect_to "/projects/#{@project.id}/budget_holders", notice: 'Budget Holder can not deleted because it is linked with its assosiative records'
    end
  end

  def import
    file = params[:file]

    File.open(Rails.root.join('public', 'documents', file.original_filename), 'wb') do |f|
      f.write(file.read)
    end

    errors = BudgetHolder.import_file(params[:file], current_user, @project)
    if errors == nil
      flash[:notice] = 'File Imported Successfully'
    else
      flash[:notice] = errors
    end
    redirect_to project_budget_holders_path
  end

  def download_template
    send_file(
        "#{Rails.root}/public/documents/budget_holders.csv",
        filename: "budget_holders.csv",
    )
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_budget_holder
    @budget_holder = BudgetHolder.find(params[:id])
  end

  def get_project
    @project = Project.find(params[:project_id])
  end

  # Only allow a list of trusted parameters through.
  def budget_holder_params
    params.require(:budget_holder).permit(:employee_id, :client_company_id)
  end
end

app/helpers/budget_holders_helper.rb
module BudgetHoldersHelper
end

app/views/budget_holders/_form.html.erb
<%= form_with(model: [@project, budget_holder], local: true) do |form| %>
  <% if budget_holder.errors.any? %>
    <%= render 'layouts/error_messages', object: form.object %>
  <% end %>

  <div class="form-row">
    <%= form.label :budget_holders, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <% if params[:action].eql?("edit") %>
          <select name="budget_holder[employee_id]" id="employee_id" class="form-control">
            <option value="<%= @budget_holder.employee.present? ? @budget_holder.employee_id : "" %>"><%= @budget_holder.employee.present? ? @budget_holder.employee.employee_name : "None" %></option>
            <% @project.employees.reject { |employee| @project.budget_holders.pluck(:employee_id).include?(employee.id) }.each do |employee| %>
              <option value="<%= employee.id %>">
                <%= employee.employee_name %>
              </option>
            <% end %>
          </select>
        <% else %>
          <%= form.select :employee_ids, options_for_select(@project.employees.reject { |employee| @project.budget_holders.pluck(:employee_id).include?(employee.id) }.map { |c| [c.employee_name, c.id] }), {}, {class: "form-control selectpicker", data: {"live-search": true}, multiple: true} %>
        <% end %>
      </div>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
      <div class="form-group mt-3 mb-0">
        <div class="actions">
          <%= form.submit 'Save', :class => 'btn bg-clr btn-style w-100' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group mt-3 mb-0">
        <div class="actions">
          <%= link_to "Cancel", project_budget_holders_path, :class => 'btn bg-clr btn-style w-100' %>
        </div>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function () {
        $('select').selectpicker();
    });
</script>

app/views/budget_holders/destroy.js.erb
<% if @destroy %>
var client_companies_path = "/projects/" + <%= @project.id %> + "/budget_holders"
location.href = client_companies_path
alert("Budget Holder deleted successfully")
<% else %>
alert("Budget Holder can not deleted because Budget Holder is linked with Project.")

<% end %>

app/views/budget_holders/edit.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">Editing Budget Holder</h4>
          </div>
          <div class="card-body">
            <%= render 'form', budget_holder: @budget_holder %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/budget_holders/index.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <main>
      <% if notice.present? %>
        <p id="notice" class="alert-success notice-style"><%= notice %></p>
      <% end %>
      <div class="form-info-style">
        <%= render 'shared/client_and_project_info' %>
      </div>
      <div class="container-fluid">
        <div class="row pt-3">
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to 'Back to Project Setup', project_path(@project), :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>

          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to "Add New Budget Holder", new_project_budget_holder_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>

<!--          <div class="col-xl-3 col-md-3">-->
<!--            <div class="card bg-success text-white mb-3">-->
              <%#= link_to 'Download Template', download_template_project_budget_holders_path, :class => "btn btn-dark", style: "color: white" %>
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-xl-3 col-md-3">-->
            <%#= form_tag import_project_budget_holders_path, multipart: true do %>
              <%#= submit_tag "Import", :class => "btn btn-dark", style: "color: white" %>
              <%#= file_field_tag :file, :required => true, class: 'pb-1' %>
            <%# end %>
<!--          </div>-->
        </div>


        <div class="card mb-4">
          <div class="card-header"><i class="fas fa-table mr-1"></i>Budget Holders</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Budget Holder</th>
                  <th>Employee Type</th>
                  <th>Project Company</th>
                  <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                <% @budget_holders.each do |budget_holder| %>
                  <tr>
                    <td><%= budget_holder.employee.employee_name rescue "N/A" %></td>
                    <td><%= Employee.find_by_id(budget_holder.employee_id).employee_type.employee_type rescue "N/A" %> </td>
                    <td><%= Employee.find_by_id(budget_holder.employee_id).project_company.company_name rescue "N/A" %></td>
                    <td>
                      <%= link_to "View", "/projects/#{@project.id}/budget_holders/#{budget_holder.id}", :class => "btn btn-outline-dark" %>
                      <%= link_to "Edit", "/projects/#{@project.id}/budget_holders/#{budget_holder.id}/edit", :class => "btn btn-outline-info" %>
                      <%= link_to "Delete", "/projects/#{@project.id}/budget_holders/#{budget_holder.id}", data: {confirm: 'Are you sure?'}, :class => "btn btn-outline-danger", method: :delete, remote: true %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

<script>
  var dataTable = $('#dataTable').DataTable({
    "columnDefs": [
        {"searchable": false, "targets": 3}
    ],
      "scrollY": "500px",
      "scrollX": "700px",
      "lengthMenu": [[50, 100, -1], [50, 100, "All"]]
  });
  document.addEventListener("turbolinks:before-cache", function() {
    if (dataTable !== null) {
      dataTable.destroy();
      dataTable = null;
    }
  });
</script>

app/views/budget_holders/new.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr text-white">
            <h4 class="text-center font-weight-light">Create Budget Holder</h4>
          </div>
          <div class="card-body">
            <%= render 'form', budget_holder: @budget_holder %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/budget_holders/show.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">View Budget Holder</h4>
          </div>
          <div class="card-body">

            <div class="form-row">
              <div class="col-md-4">
                <strong>Budget Holder Name:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @budget_holder.employee.employee_name %>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-3">
                <div class="form-group mt-3 mb-0">
                  <div class="actions">
                    <%= link_to 'Edit', edit_project_budget_holder_path(@project), :class => 'btn btn-style bg-clr w-100' %>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group mt-3 mb-0">
                  <div class="actions">
                    <%= link_to 'Back', project_budget_holders_path, :class => 'btn btn-style bg-clr w-100' %>
                  </div>
                </div>
              </div>
              <div class="col-md-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </main>
</div>