config/routes.rb
Rails.application.routes.draw do

  resources :history

  get 'timesheet/index'
  # resources :budget_holders
  # resources :plants

  resources :projects do
    resources :plant_time_sheets
    resources :employee_time_sheets
    resources :time_sheet_cost_codes
    resources :crews do
      collection do
        get '/:id/plants_list', to: 'crews#plants_list'
        get '/:id/employees_list', to: 'crews#employees_list'
      end
    end

    resources :foremen do
      collection do
        get :crew
        get :project_foreman_list
        post :import
        get :download_template
      end
    end

    resources :plants do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employee_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plant_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :cost_codes do
      collection do
        get :select_cost_codes
        post :assign_cost_codes
        post :import
        get :download_template
      end
    end

    resources :other_managers do
      collection do
        post :import
        get :download_template
      end
    end


    resources :budget_holders do
      collection do
        post :import
        get :download_template
      end
    end

    resources :project_companies do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employees do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plants


  end

  resources :temporary_users
  devise_for :users, :controllers => {:sessions => "sessions", confirmations: 'confirmations' }

  # devise_for :users, controllers: {
  #     sessions: 'users/sessions',
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations'
  # }

  root to: 'admin_dashboard#dashboard'
  resources :client_companies
  resources :users

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

end

app/models/cost_code.rb
class CostCode < ApplicationRecord
  audited
  belongs_to :project, optional: true
  belongs_to :budget_holder, optional: true

  validates_uniqueness_of :cost_code_id, :scope => :project_id, :case_sensitive => false
  auto_strip_attributes :cost_code_id


  def self.import_file(file, user, project)
    if File.extname(file.original_filename) == '.csv'
      csv_text = (File.read(file.path, :encoding => 'windows-1251:utf-8')).scrub
      csv = CSV.parse(csv_text, :headers => true)
      i = 0
      @cost_code = []
      i = 0
      csv.each do |row|
        begin
          i = i + 1
          if row[0].present?
            budget_holder = Employee.where(employee_name: row[0].strip).first
            if budget_holder.nil?
              return error = "Validation Failed. Budget Holder does not exist. Error on Row: #{i}"
            else
              row[0] = budget_holder.id
              budget_holder_id = BudgetHolder.where(employee_id: row[0].strip).first
              if budget_holder_id.nil?
                return error = "Validation Failed. Budget Holder does not exist. Error on Row: #{i}"
              else
                row[0] = budget_holder_id.id
              end
            end
          end

          if row[1].nil?
            return error = "Validation Failed. Cost Cost ID Empty in File, Error on Row: #{i}"
          end

          exist_cost_code = project.cost_codes.where("lower(cost_code_id) = ?", row[1].strip.downcase)
          if !exist_cost_code.empty?
            return error = "Validation Failed. Cost Cost Already Exist in Project, Error on Row: #{i}"
          end

          new_cost_code = @cost_code.any? {|cost_code| cost_code.cost_code_id == row[1]}
          if new_cost_code == true
            return error = "Validation Failed. Cost Cost Already Exist in File, Error on Row: #{i}"
          end


          if row[2].nil?
            return error = "Validation Failed. Cost Cost Description Empty in File, Error on Row: #{i}"
          end

          cost_code_description = project.cost_codes.where("lower(cost_code_description) = ?", row[2].strip.downcase)
          if !cost_code_description.empty?
            return error = "Validation Failed. Cost Cost Description Already Exist in Project, Error on Row: #{i}"
          end

          new_cost_code_description = @cost_code.any? {|cost_code| cost_code.cost_code_description == row[2]}
          if new_cost_code_description == true
            return error = "Validation Failed. Cost Cost Description Already Exist in File, Error on Row: #{i}"
          end

          @cost_code << project.cost_codes.new(budget_holder_id: row[0], cost_code_id: row[1], cost_code_description: row[2], WBS_01: row[3], WBS_01_Description: row[4],
                                               WBS_02: row[5], WBS_02_Description: row[6], WBS_03: row[7], WBS_03_Description: row[8],
                                               WBS_04: row[9], WBS_04_Description: row[10], WBS_05: row[11], WBS_05_Description: row[12])

        rescue => e
          return e.message
        end
      end
      if @cost_code.empty?
        return error = "Validation Failed. Please Insert some data in File."
      end
      CostCode.import @cost_code
      error = 'Data imported successfully!'
    else
      error = 'Invalid File Format. Please Import CSV Successfully'
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then
      Roo::CSV.new(file.path, nil, :ignore)
    when ".xlsx" then
      Roo::Excelx.new(file.path)
    when ".xls" then
      Roo::Excel.new(file.path)
    else
      return false
    end
  end


end

app/models/project.rb
class Project < ApplicationRecord
  audited
  belongs_to :client_company

  has_many :cost_codes, dependent: :destroy
  has_many :other_managers, dependent: :destroy
  has_many :plants, dependent: :destroy
  has_many :budget_holders, dependent: :destroy
  has_many :plant_types, dependent: :destroy
  has_many :employees, dependent: :destroy
  has_many :employee_types, dependent: :destroy
  has_many :foremen, dependent: :destroy
  has_many :employee_time_sheets, dependent: :destroy
  has_many :plant_time_sheets, dependent: :destroy
  has_many :time_sheet_cost_codes, dependent: :destroy
  has_many :project_companies

  has_many :users
  has_many :crews


  enum status: {
      Active: 0,
      Onhold: 1,
      Closed: 2
  }

  validates_uniqueness_of :project_name, :case_sensitive => false
  auto_strip_attributes :project_name


  # before_destroy :check_for_projects, prepend: true

  private

  # def check_for_projects
  #   if project_employees.any? || cost_codes.any? || other_managers.any? || plants.any? || budget_holders.any? ||
  #       plant_types.any? || employee_types.any? || foremen.any?
  #     errors[:base] << "cannot delete submission that has already been linked"
  #     return false
  #   end
  # end


end

app/controllers/cost_codes_controller.rb
class CostCodesController < ApplicationController
  load_and_authorize_resource
  before_action :set_cost_code, only: [:show, :edit, :update, :destroy]
  before_action :get_project, only: [:new, :show, :edit, :update, :create, :index, :destroy, :import, :select_cost_codes, :assign_cost_codes]

  # GET /cost_codes
  # GET /cost_codes.json
  def index
    @cost_codes = @project.cost_codes
  end

  # GET /cost_codes/1
  # GET /cost_codes/1.json
  def show
  end

  # GET /cost_codes/new
  def new
    @cost_code = CostCode.new
  end

  # GET /cost_codes/1/edit
  def edit
  end

  # POST /cost_codes
  # POST /cost_codes.json
  def create
    @cost_code = @project.cost_codes.new(cost_code_params)
    @cost_code.client_company_id = current_user.client_company_id
    respond_to do |format|
      if @cost_code.save
        format.html {redirect_to "/projects/#{@project.id}/cost_codes", notice: 'Cost code was successfully created.'}
        format.json {render :show, status: :created, location: @cost_code}
      else
        format.html {render :new}
        format.json {render json: @cost_code.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /cost_codes/1
  # PATCH/PUT /cost_codes/1.json
  def update
    respond_to do |format|
      if @cost_code.update(cost_code_params)
        format.html {redirect_to "/projects/#{@project.id}/cost_codes", notice: 'Cost code was successfully updated.'}
        format.json {render :show, status: :ok, location: @cost_code}
      else
        format.html {render :edit}
        format.json {render json: @cost_code.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /cost_codes/1
  # DELETE /cost_codes/1.json
  def destroy
    begin
      if @cost_code.nil? || TimeSheetCostCode.find_by_cost_code_id(@cost_code.id).present?
        respond_to do |format|
          format.js
        end
      else
        @cost_code.destroy
        @destroy = true
        respond_to do |format|
          format.js
        end
      end
    rescue => e
      redirect_to "/projects/#{@project.id}/cost_codes", notice: 'Cost Code can not deleted because it is linked with its assosiative records'
    end
  end

  def select_cost_codes
    @unassign_cost_codes = @project.cost_codes.where(budget_holder_id: nil)
    @budget_holders = @project.budget_holders
  end

  def assign_cost_codes
    cost_code_ids = params[:cost_code_ids].reject { |e| e.empty? }
    budget_holder_id = params[:cost_code][:budget_holder_id]
    if cost_code_ids.present? && budget_holder_id.present?
      @project.cost_codes.where(id: cost_code_ids).update_all(budget_holder_id: budget_holder_id)
      respond_to do |format|
        format.html { redirect_to project_cost_codes_path, notice: 'Cost Code Successfully Assigned' }
      end
    else
      respond_to do |format|
        format.html { redirect_to select_cost_codes_project_cost_codes_path, notice: 'Parameter Missing' }
      end
    end
  end

  def import
    file = params[:file]
    # File.open(Rails.root.join('public', 'documents', file.original_filename), 'wb') do |f|
    #   f.write(file.read)
    # end
    errors = CostCode.import_file(params[:file], current_user, @project)
    if errors == nil
      flash[:notice] = 'File Imported Successfully'
    else
      flash[:notice] = errors
    end
    redirect_to project_cost_codes_path
  end

  def download_template
    send_file(
        "#{Rails.root}/public/documents/cctemplate.csv",
        filename: "cctemplate.csv",
    )
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cost_code
    @cost_code = CostCode.find(params[:id])
  end

  def get_project
    @project = Project.find(params[:project_id])
  end

  # Only allow a list of trusted parameters through.
  def cost_code_params
    params.require(:cost_code).permit(:cost_code_id, :cost_code_description, :budget_holder_id,
                                      :WBS_01, :WBS_01_Description, :WBS_02, :WBS_02_Description,
                                      :WBS_03, :WBS_03_Description, :WBS_04, :WBS_04_Description,
                                      :WBS_05, :WBS_05_Description)
  end
end

app/helpers/cost_codes_helper.rb
module CostCodesHelper
end

app/views/cost_codes/_form.html.erb
<%= form_with(model: [@project, cost_code], local: true) do |form| %>
  <%= render 'layouts/error_messages', object: form.object %>

  <% if params[:action].eql?("edit") %>

    <div class="form-row">
      <%= form.label :budget_holder, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
      <div class="value">
        <div class="input-group">
          <select name="cost_code[budget_holder_id]" id="budget_holder" class="form-control">
            <option value="<%= @cost_code.budget_holder.present? ? @cost_code.budget_holder_id : "" %>"><%= @cost_code.budget_holder.present? ? @cost_code.budget_holder.employee.employee_name : "None" %></option>
            <% @project.budget_holders.reject {|budget_holder| budget_holder.id == @cost_code.budget_holder_id}.each do |budget_holder| %>
              <option value="<%= budget_holder.id %>">
                <%= budget_holder.employee.employee_name %>
              </option>
            <% end %>
          </select>
        </div>
      </div>
    </div>

    <% if TimeSheetCostCode.find_by_cost_code_id(@cost_code.id).present? %>
      <div class="form-row">
        <%= form.label :budget_holder_start_date, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
        <div class="value">
          <div class="input-group">
            <%= form.text_field :budget_holder_start_date, id: "new-bd-date", :class => 'form-control py-2' %>
          </div>
        </div>
      </div>

    <% end %>
  <% else %>
    <div class="form-row">
      <%= form.label :budget_holder, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
      <div class="value">
        <div class="input-group">
          <select name="cost_code[budget_holder_id]" id="budget_holder" class="form-control">
            <option value="<%= @cost_code.budget_holder.present? ? @cost_code.budget_holder_id : "" %>"><%= @cost_code.budget_holder.present? ? @cost_code.budget_holder.employee.employee_name : "None" %></option>
            <% @project.budget_holders.reject {|budget_holder| budget_holder.id == @cost_code.budget_holder_id}.each do |budget_holder| %>
              <option value="<%= budget_holder.id %>">
                <%= budget_holder.employee.employee_name %>
              </option>
            <% end %>
          </select>
        </div>
      </div>
    </div>

  <% end %>


  <div class="form-row">
    <%= form.label :cost_code_id, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <% if params[:action].eql?("edit") %>
          <%= form.text_field :cost_code_id, :class => "form-control py-2", :disabled => true %>
        <% else %>
          <%= form.text_field :cost_code_id, :class => "form-control py-2", :required => true %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :cost_code_description, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :cost_code_description, :class => "form-control py-2" , :required => true  %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_01, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_01, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_01_Description, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_01_Description, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_02, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_02, :class => "form-control py-2" %>
      </div>
    </div>
  </div>


  <div class="form-row">
    <%= form.label :WBS_02_Description, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_02_Description, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_03, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_03, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_03_Description, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_03_Description, :class => "form-control py-2" %>
      </div>
    </div>
  </div>


  <div class="form-row">
    <%= form.label :WBS_04, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_04, :class => "form-control py-2" %>
      </div>
    </div>
  </div>


  <div class="form-row">
    <%= form.label :WBS_04_Description, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_04_Description, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_05, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_05, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <%= form.label :WBS_05_Description, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :WBS_05_Description, :class => "form-control py-2" %>
      </div>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
      <div class="form-group mt-3 mb-0">
        <div class="actions">
          <%= form.submit 'Save', :class => 'btn w-100 bg-clr btn-style' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group mt-3 mb-0">
        <div class="actions">
          <%= link_to "Cancel", project_cost_codes_path, :class => 'btn w-100 bg-clr btn-style' %>
        </div>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
<% end %>
<script type="text/javascript">
    $(function () {
        $('.b-end-date').datepicker({
            format: 'yyyy-mm-dd',
        });

        $('#new-bd-date').datepicker({
            uiLibrary: 'bootstrap',
            minDate: new Date()
        });

    });
</script>

app/views/cost_codes/destroy.js.erb
<% if @destroy %>
var client_companies_path = "/projects/" + <%= @project.id %> + "/cost_codes"
location.href = client_companies_path
alert("Cost Code deleted successfully")
<% else %>
alert("Cost Code can not deleted because Cost Code is linked with Project.")

<% end %>

app/views/cost_codes/edit.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading text-white bg-clr">
            <h4 class="text-center font-weight-light">Edit Cost Code</h4>
          </div>

          <div class="card-body">
            <%= render 'form', cost_code: @cost_code %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cost_codes/index.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <main>
      <% if notice.present? %>
        <p id="notice" class="alert-success notice-style"><%= notice %></p>
      <% end %>
      <div class="form-info-style">
        <%= render 'shared/client_and_project_info' %>
      </div>
      <div class="container-fluid">
        <div class="row pt-3">
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white">
              <%= link_to 'Back to Project Setup', project_path(@project), :class => "btn btn-dark", style: "color: white" %>
            </div>
            <div class="card bg-success text-white">
              <%= link_to 'Assign Cost Codes', select_cost_codes_project_cost_codes_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>

          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white">
              <%= link_to 'New Cost Code', new_project_cost_code_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white">
              <%= link_to 'Download Template', download_template_project_cost_codes_path, :class => "btn btn-dark", style: "color: white" %>
            </div>


          </div>
          <div class="col-xl-3 col-md-3">
            <%= form_tag import_project_cost_codes_path, multipart: true do %>
              <%= submit_tag "Import", :class => "btn btn-dark", style: "color: white" %>
              <%= file_field_tag :file, :required => true, class: 'pb-1' %>
            <% end %>
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-header"><i class="fas fa-table mr-1"></i>Cost Codes</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Budget Holder</th>
                  <th>Cost Code</th>
                  <th>Cost Code Description</th>

                  <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                <% @cost_codes.each do |cost_code| %>
                  <tr>
                    <td><%= cost_code.budget_holder.employee.employee_name rescue "N/A" %></td>
                    <td><%= cost_code.cost_code_id %></td>
                    <td><%= cost_code.cost_code_description %></td>

                    <td>
                      <%= link_to 'View', "/projects/#{@project.id}/cost_codes/#{cost_code.id}", :class => "btn btn-outline-dark" %>
                      <%= link_to 'Edit', "/projects/#{@project.id}/cost_codes/#{cost_code.id}/edit", :class => "btn btn-outline-info" %>
                      <%= link_to 'Delete', "/projects/#{@project.id}/cost_codes/#{cost_code.id}", method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-outline-danger", remote: true %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

<script>
  var dataTable = $('#dataTable').DataTable({
    "columnDefs": [
        {"searchable": false, "targets": 3}
    ],
      "scrollY": "500px",
      "scrollX": "700px",
      "lengthMenu": [[50, 100, -1], [50, 100, "All"]]
  });
  document.addEventListener("turbolinks:before-cache", function() {
    if (dataTable !== null) {
      dataTable.destroy();
      dataTable = null;
    }
  });
</script>

app/views/cost_codes/new.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
<!--    <h3 class="alert-success mt-1"><%#= notice %></h3>-->
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading text-white bg-clr">
            <h4 class="text-center font-weight-light">Create Cost Code</h4>
          </div>

          <div class="card-body">
            <%= render 'form', cost_code: @cost_code %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cost_codes/select_cost_codes.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading text-white bg-clr">
            <h4 class="text-center font-weight-light">Assign Cost Code</h4>
          </div>
          <div class="card-body">

            <%= form_with url: "/projects/#{@project.id}/cost_codes/assign_cost_codes" do |form| %>

              <div class="form-row">
                <%= form.label :budget_holder, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
                <div class="value">
                  <div class="input-group">
                    <select name="cost_code[budget_holder_id]" id="budget_holder" class="form-control">
                      <option value=""></option>
                      <% @budget_holders.each do |budget_holder| %>
                        <option value="<%= budget_holder.id %>">
                          <%= budget_holder.employee.employee_name %>
                        </option>
                      <% end %>
                    </select>
                  </div>
                </div>
              </div>

              <div class="form-row">
                <%= form.label :cost_codes, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
                <div class="value">
                  <div class="input-group">
                    <% if params[:action].eql?("edit") %>
                      <select name="cost_codes[cost_code_id]" id="cost_code_id" class="form-control">
                        <% @unassign_cost_codes.each do |cost_code| %>
                          <option value="<%= cost_code.id %>">
                            <%= cost_code.cost_code_id %>
                          </option>
                        <% end %>
                      </select>
                    <% else %>
                      <%#= form.select :cost_code_ids, options_for_select(@unassign_cost_codes.reject { |cost_code| @unassign_cost_codes.pluck(:cost_code_id).include?(cost_code.id) }.map { |code| [code.cost_code_description, code.id] }), {}, {class: "form-control selectpicker", data: {"live-search": true}, multiple: true} %>
                      <%= form.select :cost_code_ids, options_for_select(@unassign_cost_codes.map {|code| [code.cost_code_id, code.id]}), {}, {class: "form-control selectpicker", data: {"live-search": true}, multiple: true} %>
                    <% end %>
                  </div>
                </div>
              </div>

              <hr>
              <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-3">
                  <div class="form-group mt-3 mb-0">
                    <div class="actions">
                      <%= form.submit 'Save', :class => 'btn w-100 bg-clr btn-style' %>
                    </div>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group mt-3 mb-0">
                    <div class="actions">
                      <%= link_to "Cancel", project_cost_codes_path, :class => 'btn w-100 bg-clr btn-style' %>
                    </div>
                  </div>
                </div>
                <div class="col-md-3"></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('select').selectpicker();
    });
</script>