config/routes.rb
Rails.application.routes.draw do

  resources :history

  get 'timesheet/index'
  # resources :budget_holders
  # resources :plants

  resources :projects do
    resources :plant_time_sheets
    resources :employee_time_sheets
    resources :time_sheet_cost_codes
    resources :crews do
      collection do
        get '/:id/plants_list', to: 'crews#plants_list'
        get '/:id/employees_list', to: 'crews#employees_list'
      end
    end

    resources :foremen do
      collection do
        get :crew
        get :project_foreman_list
        post :import
        get :download_template
      end
    end

    resources :plants do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employee_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plant_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :cost_codes do
      collection do
        get :select_cost_codes
        post :assign_cost_codes
        post :import
        get :download_template
      end
    end

    resources :other_managers do
      collection do
        post :import
        get :download_template
      end
    end


    resources :budget_holders do
      collection do
        post :import
        get :download_template
      end
    end

    resources :project_companies do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employees do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plants


  end

  resources :temporary_users
  devise_for :users, :controllers => {:sessions => "sessions", confirmations: 'confirmations' }

  # devise_for :users, controllers: {
  #     sessions: 'users/sessions',
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations'
  # }

  root to: 'admin_dashboard#dashboard'
  resources :client_companies
  resources :users

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

end

app/models/employee.rb
class Employee < ApplicationRecord
  audited

  belongs_to :client_company
  belongs_to :project_company
  belongs_to :project
  belongs_to :employee_type
  belongs_to :foreman, optional: true
  belongs_to :other_manager, optional: true
  has_many :budget_holders
  has_many :crews
  has_many :employee_time_sheets


  validates_uniqueness_of :employee_id, :scope => :project_id, :case_sensitive => false
  auto_strip_attributes :employee_id

  enum gender: {
      Male: 0,
      Female: 1
  }
  enum status: {
      Active: 0,
      Onhold: 1,
      Closed: 2
  }

  def self.import_file(file, user, project)
    if File.extname(file.original_filename) == '.csv'
      csv_text = (File.read(file.path, :encoding => 'windows-1251:utf-8')).scrub
      csv = CSV.parse(csv_text, :headers => true)
      i = 0
      @employee = []
      csv.each do |row|
        begin
          i = i + 1

          if row[0].nil? || row[1].nil? || row[2].nil? || row[3].nil? || row[5].nil? || row[6].nil? || row[12].nil?
            return error = "Validation Failed. Employee Field Empty in File, Error on Row: #{i}"
          end


          exist_employee_id = Employee.where(employee_id: row[1].strip, project_id: project.id).first
          if exist_employee_id.present?
            return error = "Validation Failed. Employee ID Exist, Error on Row: #{i}"
          end


          employee_id = @employee.any? {|a| a.employee_id.downcase == row[1].strip.downcase}
          if employee_id
            return error = "Validation Failed. Employee ID Already Exist in File, Error on Row: #{i}"
          end

          if row[11].present?
            if row[11] == 'm' || row[11] == 'M' || row[11] == 'Male' || row[11] == 'male'
              row[11] = "Male"
            elsif row[11] == 'f' || row[11] == 'F' || row[11] == 'Female' || row[11] == 'female'
              row[11] = "Female"
            else
              row[11] = "Male"
            end
          end

          if row[12].present?
            if row[12] == 'Active' || row[12] == 'a' || row[12] == 'A' || row[12] == 'active'
              row[12] = "Active"
            elsif row[12] == 'Closed' || row[12] == 'closed' || row[12] == 'c' || row[12] == 'c' || row[12] == 'close' || row[12] == 'Close'
              row[12] = "Closed"
            elsif row[12] == 'Onhold' || row[12] == 'onhold' || row[12] == 'o' || row[12] == 'O' || row[12] == 'OnHold' || row[12] == 'onHold'
              row[12] = "Onhold"
            else
              row[12] = "Active"
            end
          end

          project_company = project.project_companies.where("lower(company_name) = ?", row[3].strip.downcase).first
          if project_company.nil?
            return error = "Validation Failed. Project Company must Exist, Error on Row: #{i}"
          else
            row[3] = project_company.id
          end

          if row[10].present?
            exist_employee_email = Employee.where(email: row[10].strip, project_id: project.id)
            if !exist_employee_email.empty?
              return error = "Validation Failed. Email Already Exist, Error on Row: #{i}"
            end
          end

          start_date = Date.strptime(row[5],"%d/%m/%y") rescue nil
          if start_date.nil?
            start_date = Date.strptime(row[5],"%d.%m.%y") rescue nil
          end
          if start_date.nil?
            start_date = Date.parse(row[5])
          end
          end_date = Date.strptime(row[6],"%d/%m/%y") rescue nil
          if end_date.nil?
            end_date = Date.strptime(row[6],"%d.%m.%y") rescue nil
          end
          if end_date.nil?
            end_date = Date.parse(row[6])
          end
          if !(project.start_date..project.end_date).cover?(start_date) || !(project.start_date..project.end_date).cover?(end_date)
            return error = "Validation Failed. Date should be subset of project start and end date, Error on Row: #{i}"
          end

          if start_date > end_date
            return error = "Validation Failed. Contract End date must be after start date, Error on Row: #{i}"
          end

          if row[10].present?
            new_employee_email = @employee.any? {|a| a.email == row[10].strip}
            if new_employee_email == true
              return error = "Validation Failed. Email Already Exist in File, Error on Row: #{i}"
            end
          end

          if row[9].present?
            exist_employee_phone = Employee.where(phone: row[9].strip, project_id: project.id)
            if !exist_employee_phone.empty?
              return error = "Validation Failed. Phone Already Exist, Error on Row: #{i}"
            end
          end

          if row[9].present?
            new_employee_phone = @employee.any? {|a| a.phone == row[9].strip}
            if new_employee_phone == true
              return error = "Validation Failed. Phone Already Exist in File, Error on Row: #{i}"
            end
          end

          if row[8].present?
            other_manager = Employee.where(employee_name: row[8].strip).first
            if other_manager.nil?
              return error = "Validation Failed. Other Manager must Exist, Error on Row: #{i}"
            else
              other_manager = OtherManager.where(employee_id: other_manager.id).first
              if other_manager.nil?
                return error = "Validation Failed. Other Manager must Exist, Error on Row: #{i}"
              else
                row[8] = other_manager.id
              end
            end
          end

          if row[7].present?
            foreman = Employee.where(employee_name: row[7].strip).first
            if foreman.nil?
              return error = "Validation Failed. Foreman must Exist, Error on Row: #{i}"
            else
              foreman = Foreman.where(employee_id: foreman.id).first
              if foreman.nil?
                return error = "Validation Failed. Foreman must Exist, Error on Row: #{i}"
              else
                row[7] = foreman.id
              end
            end
          end

          plant_type = EmployeeType.where(employee_type: row[2].strip).first
          if plant_type.nil?
            return error = "Validation Failed. Employee Type must Exist, Error on Row: #{i}"
          else
            row[2] = plant_type.id
          end

          @employee << project.employees.new(employee_name: row[0], employee_id: row[1], employee_type_id: row[2], project_company_id: row[3], home_company_role: row[4], contract_start_date: start_date,
                                             contract_end_date: end_date, foreman_id: row[7], other_manager_id: row[8], phone: row[9], email: row[10], gender: row[11],
                                             status: row[12], client_company_id: project.client_company_id,
                                             foreman_start_date: start_date)

        rescue => e
          return e.message
        end
      end

      if @employee.empty?
        return error = "Validation Failed. Please Insert some data in File."
      end
      @employee.each do |employee|
        project_company = ProjectCompany.find_by_id(employee.project_company_id)
        project_company.update(number_of_employee: project_company.number_of_employee + 1) if project_company.present?
      end

      Employee.import @employee
      error = 'Data imported successfully!'
    else
      error = 'Invalid File Format. Please Import CSV Successfully'

    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then
      Roo::CSV.new(file.path, nil, :ignore)
    when ".xlsx" then
      Roo::Excelx.new(file.path)
    when ".xls" then
      Roo::Excel.new(file.path)
    else
      return false
    end
  end

end

app/models/employee_type.rb
class EmployeeType < ApplicationRecord
  audited
  belongs_to :project
  has_many :employees

  validates_uniqueness_of :employee_type, :scope => :project_id, :case_sensitive => false
  auto_strip_attributes :employee_type

  def self.import_file(file, project)
    if File.extname(file.original_filename) == '.csv'
      csv_text = (File.read(file.path, :encoding => 'windows-1251:utf-8')).scrub
      csv = CSV.parse(csv_text, :headers => true)
      i = 0
      @employee_type = []
      csv.each do |row|
        begin
          i = i + 1
          if row[0].nil?
            return error = "Validation Failed. Employee Type Empty in File, Error on Row: #{i}"
          end

          exist_employee_type = project.employee_types.where("lower(employee_type) = ?", row[0].strip.downcase)
          if exist_employee_type.present?
            return error = "Validation Failed. Employee Type Already Exist in Project, Error on Row: #{i}"
          end

          new_employee_type = @employee_type.any? {|a| a.employee_type.downcase == row[0].strip.downcase}
          if new_employee_type == true
            return error = "Validation Failed.Employee Type Already Exist in File, Error on Row: #{i}"
          end

          @employee_type << project.employee_types.new(employee_type: row[0].strip, project_id: project.id, client_company_id: project.client_company_id)

        rescue => e
          return e.message
        end
      end
      if @employee_type.empty?
        return error = "Validation Failed. Please Insert some data in File."
      end
      EmployeeType.import @employee_type
      error = 'Data imported successfully!'
    else
      error = 'Invalid file format. Please upload CSV file'
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then
      Roo::CSV.new(file.path, nil, :ignore)
    when ".xlsx" then
      Roo::Excelx.new(file.path)
    when ".xls" then
      Roo::Excel.new(file.path)
    else
      return false
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  include EmployeesHelper
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :get_project, only: [:new, :show, :edit, :update, :create, :index, :import, :destroy]
  load_and_authorize_resource
  # GET /employees
  # GET /employees.json
  def index
    @employees = @project.employees
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create

    @employee = @project.employees.new(employee_params)
    if ((@project.start_date..@project.end_date).cover?(@employee.contract_start_date)) &&
        (@project.start_date..@project.end_date).cover?(@employee.contract_end_date)
      @employee.client_company_id = @project.client_company_id
      @employee.country_name = @project.client_company.country_name
      @employee.foreman_start_date = @employee.contract_start_date

      respond_to do |format|
        if @employee.save
          @employee.project_company.update(number_of_employee: @employee.project_company.number_of_employee + 1) rescue nil
          format.html { redirect_to "/projects/#{@project.id}/employees", notice: 'Employee was successfully created.' }
          format.json { render :show, status: :created, location: @employee }
        else
          format.html { render :new }
          format.json { render json: @employee.errors, status: :unprocessable_entity }
        end
      end
    else
      @employee.errors.add(:base, 'Date should be sub set of project start and end date.')
      render :action => 'new'
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    # if ((@project.start_date..@project.end_date).cover?(params[:employee][:foreman_start_date]))
      respond_to do |format|
        if @employee.update(employee_params)
          format.html { redirect_to "/projects/#{@project.id}/employees", notice: 'Employee was successfully updated.' }
          format.json { render :show, status: :ok, location: @employee }
        else
          format.html { render :edit }
          format.json { render json: @employee.errors, status: :unprocessable_entity }
        end
      end
    # else
    #   @employee.errors.add(:base, 'Date should be sub set of project start and end date.')
    #   render :action => 'edit'
    # end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    begin
      if @employee.other_manager.present? || @employee.budget_holders.present? || @employee.foreman.present? ||
          Foreman.find_by_employee_id(@employee.id) || BudgetHolder.find_by_employee_id(@employee.id) ||
          OtherManager.find_by_employee_id(@employee.id) || @employee.employee_time_sheets.present?
        respond_to do |format|
          format.js
        end
      else
        @employee.project_company.update(number_of_employee: @employee.project_company.number_of_employee - 1)
        @employee.destroy
        @destroy = true
        respond_to do |format|
          format.js
        end
      end
    rescue => e
      redirect_to project_employees_path, notice: e.message
    end
  end

  def import
    errors = Employee.import_file(params[:file], current_user, @project)
    if errors == nil
      flash[:notice] = 'File Imported Successfully'
    else
      flash[:notice] = errors
    end
    redirect_to project_employees_path
  end

  def download_template
    send_file(
        "#{Rails.root}/public/documents/etemplate.csv",
        filename: "etemplate.csv",
    )
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find_by_id(params[:id])
  end

  def get_project
    @project = Project.find(params[:project_id])
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    employe_params = params.require(:employee).permit(:first_name, :last_name,
                                                      :employee_id, :phone, :email, :employee_type_id,
                                                      :gender, :home_company_role, :employee_name,
                                                      :contract_start_date, :contract_end_date, :phone_country_code,
                                                      :status, :project_company_id, :project_id,
                                                      :other_manager_id, :foreman_id, :project_role,
                                                      :employee_type_id, :country_name, :client_company_id,
                                                      :foreman_start_date)
    employe_params[:gender] = params[:employee][:gender].to_i if params[:employee][:gender].present?
    employe_params[:status] = params[:employee][:status].to_i
    return employe_params
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper

  # def client_company_project_employees
  #   project_ids = current_user.client_company.projects.pluck(:id) rescue nil
  #   @client_company_project_employees = Employee.all.where(project_id: project_ids) rescue nil
  # end
end

app/views/employees/destroy.js.erb
<% if @destroy %>
var client_companies_path = "/projects/" + <%= @project.id %> + "/employees"
location.href = client_companies_path
alert("Employee deleted successfully")
<% else %>
alert("Employee can not deleted because Employee is linked with associative records.")

<% end %>

app/views/employees/edit.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">Edit <%= @employee.employee_name %></h4>
          </div>
          <div class="card-body">
            <%= render 'form', employee: @employee %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <main>
      <% if notice.present? %>
        <p id="notice" class="alert-success notice-style"><%= notice %></p>
      <% end %>
      <div class="form-info-style">
        <%= render 'shared/client_and_project_info' %>
      </div>
      <div class="container-fluid">
        <div class="row pt-3">
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to 'Back to Project Setup', project_path(@project), :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to 'New Employee', new_project_employee_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to 'Download Template', download_template_project_employees_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>
          <div class="col-xl-3 col-md-3">
            <%= form_tag import_project_employees_path, multipart: true do %>
              <%= submit_tag "Import", :class => "btn btn-dark", style: "color: white" %>
              <%= file_field_tag :file, :required => true, class: "pb-1" %>
            <% end %>
          </div>
        </div>

        <div class="card mb-4">
          <div class="card-header"><i class="fas fa-table mr-1"></i>Employees</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Employee ID</th>
                  <th>Employee Name</th>
                  <th>Employee Type</th>
                  <th>Project Company</th>
                  <th>Contract Start Date</th>
                  <th>Contract End Date</th>
                  <th>Foreman</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                <% @employees.each do |employee| %>
                  <tr>
                    <td><%= employee.employee_id %></td>
                    <td><%= employee.employee_name %></td>
                    <td><%= employee.employee_type.employee_type rescue "N/A" %></td>
                    <td><%= employee.project_company.company_name rescue "N/A" %></td>
                    <td><%= employee.contract_start_date %></td>
                    <td><%= employee.contract_end_date %></td>
                    <td><%= Employee.find_by_id(employee.foreman.employee_id).employee_name rescue "N/A" %></td>
                    <td><%= employee.status %></td>
                    <td><%= link_to 'View', "/projects/#{@project.id}/employees/#{employee.id}", :class => "btn btn-outline-dark" %>
                      <%= link_to 'Edit', "/projects/#{@project.id}/employees/#{employee.id}/edit", :class => "btn btn-outline-info" %>
                      <%= link_to 'Delete', "/projects/#{@project.id}/employees/#{employee.id}", method: :delete, data: {confirm: 'Are you sure?'}, remote: true, :class => "btn btn-outline-danger" %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
              <br>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

<script>
  var dataTable = $('#dataTable').DataTable({
    "columnDefs": [
        {"searchable": false, "targets": 3}
    ],
      "scrollY": "500px",
      "scrollX": "700px",
      "lengthMenu": [[50, 100, -1], [50, 100, "All"]]
  });
  document.addEventListener("turbolinks:before-cache", function() {
    if (dataTable !== null) {
      dataTable.destroy();
      dataTable = null;
    }
  });
</script>

app/views/employees/new.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">Create Client Employee</h4>
          </div>
          <div class="card-body">
            <%= render 'form', employee: @employee %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light text-white">
              Employee
            </h4>
          </div>
          <div class="card-body">

            <div class="form-row">
              <div class="col-md-4">
                <strong>Employee Name:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.employee_name %>
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-md-4">
                <strong>Employee ID:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.employee_id %>
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-md-4">
                <strong>Phone:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.phone.present? ?  @employee.phone_country_code.to_s + @employee.phone : "N/A" %>
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-md-4">
                <strong>Email:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.email %>
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-md-4">
                <strong>Gender:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.gender %>
                </div>
              </div>
            </div>

            <div class="form-row ">
              <div class="col-md-4">
                <strong>Home company role:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.home_company_role %>
                </div>
              </div>
            </div>


            <div class="form-row">
              <div class="col-md-4">
                <strong>Status:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.status %>
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-md-4">
                <strong>Project company:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee.project_company.company_name %>
                </div>
              </div>
            </div>

            <hr>
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-3">
                <div class="form-group mt-3 mb-0">
                  <div class="actions">
                    <%= link_to 'Edit', edit_project_employee_path(@project), :class => 'btn btn-style bg-clr w-100' %>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group mt-3 mb-0">
                  <div class="actions">
                    <%= link_to 'Back', project_employees_path, :class => 'btn btn-style bg-clr w-100' %>
                  </div>
                </div>
              </div>
              <div class="col-md-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>