config/routes.rb
Rails.application.routes.draw do

  resources :history

  get 'timesheet/index'
  # resources :budget_holders
  # resources :plants

  resources :projects do
    resources :plant_time_sheets
    resources :employee_time_sheets
    resources :time_sheet_cost_codes
    resources :crews do
      collection do
        get '/:id/plants_list', to: 'crews#plants_list'
        get '/:id/employees_list', to: 'crews#employees_list'
      end
    end

    resources :foremen do
      collection do
        get :crew
        get :project_foreman_list
        post :import
        get :download_template
      end
    end

    resources :plants do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employee_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plant_types do
      collection do
        post :import
        get :download_template
      end
    end

    resources :cost_codes do
      collection do
        get :select_cost_codes
        post :assign_cost_codes
        post :import
        get :download_template
      end
    end

    resources :other_managers do
      collection do
        post :import
        get :download_template
      end
    end


    resources :budget_holders do
      collection do
        post :import
        get :download_template
      end
    end

    resources :project_companies do
      collection do
        post :import
        get :download_template
      end
    end

    resources :employees do
      collection do
        post :import
        get :download_template
      end
    end

    resources :plants


  end

  resources :temporary_users
  devise_for :users, :controllers => {:sessions => "sessions", confirmations: 'confirmations' }

  # devise_for :users, controllers: {
  #     sessions: 'users/sessions',
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations'
  # }

  root to: 'admin_dashboard#dashboard'
  resources :client_companies
  resources :users

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'

end

app/controllers/employee_types_controller.rb
class EmployeeTypesController < ApplicationController
  before_action :set_employee_type, only: [:show, :edit, :update, :destroy]
  before_action :get_project, only: [:new, :show, :edit, :update, :create, :index, :import, :destroy]
  load_and_authorize_resource

  # GET /employee_types
  # GET /employee_types.json
  def index
    @employee_types = @project.employee_types rescue []
  end

  # GET /employee_types/1
  # GET /employee_types/1.json
  def show
  end

  # GET /employee_types/new
  def new
    @employee_type = EmployeeType.new
  end

  # GET /employee_types/1/edit
  def edit
  end

  # POST /employee_types
  # POST /employee_types.json
  def create
    @employee_type = @project.employee_types.new(employee_type_params)
    respond_to do |format|
      if @employee_type.save
        format.html {redirect_to "/projects/#{@project.id}/employee_types", notice: 'Employee type was successfully created.'}
        format.json {render :show, status: :created, location: @employee_type}
      else
        format.html {render :new}
        format.json {render json: @employee_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /employee_types/1
  # PATCH/PUT /employee_types/1.json
  def update
    respond_to do |format|
      if @employee_type.update(employee_type_params)
        format.html {redirect_to "/projects/#{@project.id}/employee_types", notice: 'Employee type was successfully updated.'}
        format.json {render :show, status: :ok, location: @employee_type}
      else
        format.html {render :edit}
        format.json {render json: @employee_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /employee_types/1
  # DELETE /employee_types/1.json
  def destroy
    begin
      if @employee_type.nil? || Employee.find_by_employee_type_id(@employee_type.id).present?
        respond_to do |format|
          format.js
        end
      else
        if @employee_type.destroy
          @destroy = true
        else
        end
        respond_to do |format|
          format.js
        end
      end
    rescue => e
      redirect_to "/projects/#{@project.id}/employee_types", notice: 'Employee Type can not deleted because it is linked with its assosiative records'
    end

  end

  def import
    file = params[:file]

    errors = EmployeeType.import_file(params[:file], @project)
    if errors == nil
      flash[:notice] = 'File Imported Successfully'
    else
      flash[:notice] = errors
    end
    redirect_to project_employee_types_path
  end

  def download_template
    send_file(
        "#{Rails.root}/public/documents/employee_type_template.csv",
        filename: "employee_type_template.csv",
    )
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee_type
    @employee_type = EmployeeType.find(params[:id])
  end

  def get_project
    @project = Project.find(params[:project_id])
  end

  # Only allow a list of trusted parameters through.
  def employee_type_params
    params.require(:employee_type).permit(:employee_type)
  end
end

app/helpers/employee_types_helper.rb
module EmployeeTypesHelper
end

app/views/employee_types/_form.html.erb
<%= form_with(model: [@project, employee_type], local: true) do |form| %>
  <%= render 'layouts/error_messages', object: form.object %>

  <div class="form-row">
      <%= form.label :employee_type, :class => "mb-1 pt-2 name", :style => 'font-weight:bold' %>
    <div class="value">
      <div class="input-group">
        <% if @employee_type.employees.present? %>
          <%= form.text_field :employee_type, :class => "form-control py-2", :readonly => true %>
        <% else %>
          <%= form.text_field :employee_type, :class => "form-control py-2", :required => true %>
        <% end %>
      </div>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-3">
      <div class="form-group mt-3 mb-0">
        <div class="actions">
          <%= form.submit 'Save', :class => 'btn btn-style bg-clr w-100' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group mt-3 mb-0">
        <div class="actions">
          <%= link_to "Cancel", project_employee_types_path, :class => 'btn btn-style bg-clr w-100' %>
        </div>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function () {
        $('select').selectpicker();
    });
</script>

app/views/employee_types/destroy.js.erb
<% if @destroy %>
var client_companies_path = "/projects/" + <%= @project.id %> + "/employee_types"
location.href = client_companies_path
alert("Employee Type deleted successfully")
<% else %>
alert("Employee Type can not deleted because Employee Type is linked with associative records.")

<% end %>

app/views/employee_types/edit.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">Edit <%= @employee_type.employee_type %></h4>
          </div>

          <div class="card-body">
            <%= render 'form', employee_type: @employee_type %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employee_types/index.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <main>
      <% if notice.present? %>
        <p id="notice" class="alert-success notice-style"><%= notice %></p>
      <% end %>
      <div class="form-info-style">
        <%= render 'shared/client_and_project_info' %>
      </div>
      <div class="container-fluid">
        <div class="row pt-3">
          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to "Back to Project Setup", project_path(@project), :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>

          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to "Add New Employee Type", new_project_employee_type_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>

          <div class="col-xl-3 col-md-3">
            <div class="card bg-success text-white mb-3">
              <%= link_to 'Download Template', download_template_project_employee_types_path, :class => "btn btn-dark", style: "color: white" %>
            </div>
          </div>
          <div class="col-xl-3 col-md-3">
            <%= form_tag import_project_employee_types_path, multipart: true do %>
              <%= submit_tag "Import", :class => "btn btn-dark", style: "color: white" %>
              <%= file_field_tag :file, :required => true, class: 'pb-1' %>
            <% end %>
          </div>
        </div>

        <div class="card mb-4">
          <div class="card-header"><i class="fas fa-table mr-1"></i>Employee Types</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Employee Types</th>
                  <th>Actions</th>
                </tr>
                </thead>

                <tbody>
                <% @employee_types.each do |employee_type| %>
                  <tr>
                    <td><%= employee_type.employee_type %></td>
                    <td>
                      <%= link_to "View", "/projects/#{@project.id}/employee_types/#{employee_type.id}", :class => "btn btn-outline-dark" %>
                      <%= link_to "Edit", "/projects/#{@project.id}/employee_types/#{employee_type.id}/edit", :class => "btn btn-outline-info" %>
                      <%= link_to "Delete", "/projects/#{@project.id}/employee_types/#{employee_type.id}" + "?delete=true", data: {confirm: 'Are you sure?'}, :class => "btn btn-outline-danger", method: :delete, remote: true %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

<script>
  var dataTable = $('#dataTable').DataTable({
    "columnDefs": [
        {"searchable": false, "targets": 1}
    ],
      "scrollY": "500px",
      "scrollX": "700px",
      "lengthMenu": [[50, 100, -1], [50, 100, "All"]]
  });
  document.addEventListener("turbolinks:before-cache", function() {
    if (dataTable !== null) {
      dataTable.destroy();
      dataTable = null;
    }
  });
</script>

app/views/employee_types/new.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">Create Employee Type</h4>
          </div>
          <div class="card-body">
            <%= render 'form', employee_type: @employee_type %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employee_types/show.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_content">
    <% if notice.present? %>
      <p id="notice" class="alert-success notice-style"><%= notice %></p>
    <% end %>
    <div class="form-info-style">
      <%= render 'shared/client_and_project_info' %>
    </div>
    <div class="page-wrapper p-b-50">
      <div class="wrapper wrapper--w790">
        <div class="card card-5 form-border-style">
          <div class="card-heading bg-clr card-text-clr">
            <h4 class="text-center font-weight-light">
              Employee Type
            </h4>
          </div>
          <div class="card-body">

            <div class="form-row pt-2">
              <div class="col-md-4">
                <strong>Employee type:</strong>
              </div>
              <div class="col-md-6">
                <div>
                  <%= @employee_type.employee_type %>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-3">
                <div class="form-group mt-3 mb-0">
                  <div class="actions">
                    <%= link_to 'Edit', edit_project_employee_type_path(@project), :class => 'btn btn-style bg-clr w-100' %>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group mt-3 mb-0">
                  <div class="actions">
                    <%= link_to 'Back', project_employee_types_path, :class => 'btn btn-style bg-clr w-100' %>
                  </div>
                </div>
              </div>
              <div class="col-md-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>